### ISSUE TITLE
Major version increase?

### ISSUE THREAD

**Issue by staticdev** [pytest-dev/pytest-mock#204] opened 2020-08-24 22:03 UTC
Hi, 

I've seen 3.3.0 changed name from MockFixture to MockerFixture. It broke existing code like in:
https://github.com/staticdev/toml-validator/pull/157/checks?check_run_id=1020396590

I see at least two possible solutions here: increasing the major version to 4.0.0 to semantically say it broke original API or rename back (maybe even creating some alias to support both names).

**Comment by The-Compiler** [comment] 2020-08-24 22:05
Duplicate of #202 - keeping this open for now though.

**Comment by nicoddemus** [comment] 2020-08-25 00:17
Hi @staticdev,

> I see... sorry for the duplicate. 

No worries!

> Anyhow, @nicoddemus my test code also uses the type MockFixture to annotate arguments of fixtures such as the example code linked.

You can't upgrade because you intend to support older `pytest-mock` versions for now?

I think the only thing we can do to mitigate this is to add an alias, as you suggest, however I would prefer to avoid that because it is another thing to eventually deprecate/remove in the future.

**Comment by staticdev** [comment] 2020-08-25 00:20
@nicoddemus I don't intend to support older pytest-mock. Personally, I would go for 4.0.0 and move on.

**Comment by nicoddemus** [comment] 2020-08-25 00:22
Problem is that there's two scenarios:

1. People who pin to avoid major versions (for example `pytest-mock<3`): for those people making a new 4.0 release won't do any good, as they will still get 3.3 with `MockerFixture`.
2. People who don't pin (the vast majority I believe): those will either pin to !=3.3 or just update their code. Again won't do much good as they will need to update their code or their pins.

So unless I'm missing something, releasing 4.0 will only bring more confusion than solving any real problem, I think.

**Comment by graingert** [comment] 2020-08-25 00:32
Doesn't `reveal_type(pytest_mock.plugin.MockFixture)` just show Any?

**Comment by staticdev** [comment] 2020-08-25 00:32
I pin all my versions. To solve everything you can rename and patch 3.3.0 with 3.3.1 (go back to previous MockFixture.
And then create a 4.0.0 with MockerFixture (if you really want to rename it).

The idea of alias, as you said, comes with more code to maintain.

**Comment by nicoddemus** [comment] 2020-08-25 00:36
> The idea of alias, as you said, comes with more code to maintain.

Indeed, but just a single line in this case.

@graingert @staticdev please see https://github.com/pytest-dev/pytest-mock/pull/205.

**Comment by staticdev** [comment] 2020-08-25 00:38
@nicoddemus very well.. that does the trick! So we can close this one.

**Comment by nicoddemus** [comment] 2020-08-25 00:41
Feel free to leave your approval there. 😉

**Comment by graingert** [comment] 2020-08-25 00:42
> > The idea of alias, as you said, comes with more code to maintain.
> 
> Indeed, but just a single line in this case.
> 
> @graingert @staticdev please see #205.

No I mean in @staticdev 's codebase you're not using `-- --disallow-any-unimported` which should fail for this unexported symbol

**Comment by nicoddemus** [comment] 2020-08-25 01:16
@graingert want to take a look at #205 and see if I'm missing something?

**Closed** 2020-08-26 10:44 UTC
