### ISSUE TITLE
fixture 'mocker' not found

### ISSUE THREAD

**Issue by jaimemarijke** [pytest-dev/pytest-mock#70] opened 2016-11-08 19:50 UTC
I haven't looked too closely into this bug yet, but the error itself is strange, given that it explicitly lists 'mocker' as one of the available fixtures. 

I had run tox -r previously and everything passed. Then I upgraded

- pytest (2.9.2) -> 3.0.3
- pytest-mock (1.2) -> 1.4.0

And started seeing this failure.

```
  @pytest.fixture
  def request(mocker):
E       fixture 'mocker' not found
>       available fixtures: cache, capfd, capsys, doctest_namespace, mock, mocker, monkeypatch, pytestconfig, record_xml_property, recwarn, request, requests_get, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

```

Code looks something like this:

```
import pytest
from mock import Mock, sentinel
from requests import codes

@pytest.fixture
def request(mocker):
    return Mock((), url='https://test-url.com:8000', cookies=None, headers={})
```

**Comment by nicoddemus** [comment] 2016-11-08 20:28
I think I know what's happening.

I see you are defining a fixture named `request`. The problem is that pytest also has a builtin fixture named [request](http://doc.pytest.org/en/latest/builtin.html?highlight=request#_pytest.fixtures.FixtureRequest) which is used for a lot of things like getting options, the name of the test being executed, registering finalizers, etc.

Before version `1.4.0`, the `mocker` fixture didn't depend on other fixtures, but on `1.4.0` due to the [new `mock_use_standalone_module`](https://github.com/pytest-dev/pytest-mock/blob/master/CHANGELOG.rst#140) configuration option it now depends on the builtin `request` fixture to lookup the option's value. So the `mocker` fixture asks for a `request` fixture and gets your fixture definition instead, which in turn also depends on `mocker` so the "mocker fixture stack" blows and pytest assumes that there's no `mocker` fixture (we should improve that message somehow).

I see a few possibilities:

1. Rename `request` to something else (`myrequest`?); as you can see it is an important fixture so it may break in unexpected ways, so that's what I would do; 
2. Your `request` fixture doesn't even use `mocker`, so you may take out the parameter and things should just work (for now).

Hope that makes sense, let me know if you have any questions.

**Comment by jaimemarijke** [comment] 2016-11-08 20:59
Thanks for the speedy reply and explanation! I will try this out and let you know if it fixes my problem. 

+1 for improving the error message :). It was confusing that the error was that "fixture 'mocker' not found" but that "mocker" was listed in available fixtures.

**Comment by nicoddemus** [comment] 2016-11-08 21:01
Sure, let me know how that goes so we can close this if one of the solutions is good enough.

**Comment by jaimemarijke** [comment] 2016-11-08 22:31
Looks like removing the unused 'mocker' fixture fixed the problem, thanks again! 

If you do close this, should I open a separate issue for improving the error message?

**Comment by nicoddemus** [comment] 2016-11-08 23:09
Yes please. 😁 

Closing this then.

**Closed by nicoddemus** 2016-11-08 23:09 UTC
Labels: question

**Comment by Dishanka13** [comment] 2019-02-20 07:45
can anyone help me with this error
 def test_getproject(mocker):
          conversationService = ConversationService()
          mocker.patch.object(conversationService ,'getDoc()',return_value="None")
          assert conversationService.getDoc()==None
          res=DialogueService.getproject()
          assert res=="None"
 am getting error as
 def test_getproject(mocker):
E       fixture 'mocker' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory

**Comment by nicoddemus** [comment] 2019-02-20 11:25
Hi @Dishanka13, did you install `pytest-mock` using `pip install pytest-mock`?

You can verify that by calling `pip list`

**Comment by BlackestDawn** [comment] 2019-12-06 08:40
Not sure if still relevant but I found that I had to install pytest-mock into my user-level general python module-library (~/.local/lib/python*) when running from a venv, even though that venv had the pytest-mock package installed and relevant executables ran from the venv.

**Comment by Hettomei** [comment] 2020-08-18 12:47
FWIW

I m a newby with python.

I have to maintain an app with `pyenv` + `virtualenv` 

I have this same error `fixture 'mocker' not found` even if I have done `pip install ...` or update `pip install -r requirements-dev.txt`

My solution was to create a new `pyenv` and to create a new `virtualenv` + `pip install -r requirements-dev.txt` and then everything worked.

thanks @BlackestDawn you helped me understand this.

**Comment by dilnasaran** [comment] 2020-09-30 16:10
> Not sure if still relevant but I found that I had to install pytest-mock into my user-level general python module-library (~/.local/lib/python*) when running from a venv, even though that venv had the pytest-mock package installed and relevant executables ran from the venv.

thanks @BlackestDawn . This helped me solve my issue. Do you have any idea why this is needed?

**Comment by The-Compiler** [comment] 2020-09-30 16:31
@BlackestDawn @dilnasaran Are you sure `pytest` is really picking up your virtualenv's pytest? Using `pytest --version --version` should tell you where it was imported from and which plugins it found.

**Comment by dilnasaran** [comment] 2020-09-30 16:45
> @BlackestDawn @dilnasaran Are you sure `pytest` is really picking up your virtualenv's pytest? Using `pytest --version --version` should tell you where it was imported from and which plugins it found.

@The-Compiler I just checked it , pytest is being imported from the virtualenv.

**Comment by The-Compiler** [comment] 2020-09-30 16:57
What about the `pytest-mock` plugin if you don't install it user-wide? Is it listed there? Is it listed in `python3 -m pip freeze` (with the virtualenv's python3)?

**Comment by dilnasaran** [comment] 2020-10-02 07:16
@The-Compiler  Yes, the pytest-mock plugin is listed in the virtualenv and still I had the error "fixture 'mocker' not found". It only stopped appearing after I installed pytest-mock it in the user wide python.

**Comment by The-Compiler** [comment] 2020-10-02 07:37
@dilnasaran In a recent version? The `mock` fixture was renamed to `mocker` in 0.4.0.

**Comment by nikhilteja91** [comment] 2021-01-26 08:37
> Hi @Dishanka13, did you install `pytest-mock` using `pip install pytest-mock`?
> 
> You can verify that by calling `pip list`

it worked. thank you.
