### ISSUE TITLE
Mocker fixture fails to patch class

### ISSUE THREAD

**Issue by richin13** [pytest-dev/pytest-mock#128] opened 2018-10-31 18:41 UTC
I am trying to patch a class within one of my application submodules using the `pytest-mocker` fixture. The patch is not successfully applied because when I try `assert MyMock.call_count == 1` it says that MyMock was called 0 times, even when in my function under test I invoked my class' constructor.

I added a different test using `unittest.mock` instead of the `mocker` fixture and it works as expected.

I put together a small example that replicates the issue, is located here https://github.com/richin13/pytest-mock-behavior

I am wondering if there's anything I'm missing when trying to patch a class using the `mocker` fixture or if this is a bug

I would appreciate any help. I'm using python 3.7

**Comment by nicoddemus** [comment] 2018-10-31 23:00
Hi @richin13,

Thanks for putting together a reproducible example in a repository, appreciate it.

The problem is that you are using the `mocker` with a `with` statement. The mocker fixture was created mostly to avoid having to do this (see [rationale](https://github.com/pytest-dev/pytest-mock#why-bother-with-a-plugin)).

You also don't need to import `mocker`, as a pytest fixture, it will be injected automatically in your tests.

Here's the patch which fixes the test:

```diff
--- a/tests/test_twitter_with_mocker.py
+++ b/tests/test_twitter_with_mocker.py
@@ -1,14 +1,13 @@
 import pytest
-from pytest_mock import mocker

 from pkg.twitter import Twitter, my_awesome_func


 def test_vault(mocker):
-    with mocker.patch('pkg.twitter.Twitter') as MockTwitter:
-        MockTwitter.configure(
-            get={"testing": True}
-        )
+    MockTwitter = mocker.patch('pkg.twitter.Twitter')
+    MockTwitter.configure(
+        get={"testing": True}
+    )

-        my_awesome_func()
-        assert MockTwitter.call_count == 1
+    my_awesome_func()
+    assert MockTwitter.call_count == 1
``` 

I'm closing this for now, but feel free to follow up with further questions.

**Closed by nicoddemus** 2018-10-31 23:00 UTC

**Comment by richin13** [comment] 2018-11-01 14:17
Thank you, later I found that section in the documentation. My bad :D
