### ISSUE TITLE
[1.11.2] Tests fails

### ISSUE THREAD

**Issue by tuxmaster5000** [pytest-dev/pytest-mock#167] opened 2019-10-25 07:48 UTC
Hello I have tried to run the tests. But some was failed:

```
> + /usr/bin/python3 -m pytest
> ============================= test session starts ==============================
> platform linux -- Python 3.6.8, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
> rootdir: /builddir/build/BUILD/pytest-mock-1.11.2, inifile: tox.ini
> plugins: mock-1.11.2, cov-2.7.1, hypothesis-3.12.0
> collected 53 items
> 
> tests/test_pytest_mock.py ......................................FF...... [ 86%]
> .FF....                                                                  [100%]
> 
> =================================== FAILURES ===================================
> __________________ test_assert_called_args_with_introspection __________________
> 
> left = ('a', 1, {'test'}), right = ('b', 2, {'jest'})
> 
>     @contextmanager
>     def assert_argument_introspection(left, right):
>         """
>         Assert detailed argument introspection is used
>         """
>         try:
> >           yield
> 
> tests/test_pytest_mock.py:410: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> mocker = <pytest_mock.plugin.MockFixture object at 0x7f597696eb00>
> 
>     @pytest.mark.usefixtures("needs_assert_rewrite")
>     def test_assert_called_args_with_introspection(mocker):
>         stub = mocker.stub()
>     
>         complex_args = ("a", 1, set(["test"]))
>         wrong_args = ("b", 2, set(["jest"]))
>     
>         stub(*complex_args)
>         stub.assert_called_with(*complex_args)
>         stub.assert_called_once_with(*complex_args)
>     
>         with assert_argument_introspection(complex_args, wrong_args):
> >           stub.assert_called_with(*wrong_args)
> 
> tests/test_pytest_mock.py:488: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> args = (<MagicMock spec='function' id='140022218418496'>, 'b', 2, {'jest'})
> kwargs = {}, __tracebackhide__ = True
> 
>     def wrap_assert_called_with(*args, **kwargs):
>         __tracebackhide__ = True
> >       assert_wrapper(_mock_module_originals["assert_called_with"], *args, **kwargs)
> 
> ../../BUILDROOT/python-pytest-mock-1.11.2-1.el7.x86_64/usr/lib/python3.6/site-packages/pytest_mock/plugin.py:253: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> __wrapped_mock_method__ = <function NonCallableMock.assert_called_with at 0x7f5977652ea0>
> args = (<MagicMock spec='function' id='140022218418496'>, 'b', 2, {'jest'})
> kwargs = {}, __tracebackhide__ = True
> e = AssertionError("Expected call: mock('b', 2, {'jest'})\nActual call: mock('a', 1, {'test'})\n\npytest introspection follows:\n\nArgs:\n",)
> msg = "Expected call: mock('b', 2, {'jest'})\nActual call: mock('a', 1, {'test'})\n\npytest introspection follows:\n\nArgs:\n"
> __mock_self = <MagicMock spec='function' id='140022218418496'>
> actual_args = ('a', 1, {'test'}), actual_kwargs = {}
> introspection = '\nArgs:\n'
> 
>     def assert_wrapper(__wrapped_mock_method__, *args, **kwargs):
>         __tracebackhide__ = True
>         try:
>             __wrapped_mock_method__(*args, **kwargs)
>             return
>         except AssertionError as e:
>             if getattr(e, "_mock_introspection_applied", 0):
>                 msg = text_type(e)
>             else:
>                 __mock_self = args[0]
>                 msg = text_type(e)
>                 if __mock_self.call_args is not None:
>                     actual_args, actual_kwargs = __mock_self.call_args
>                     introspection = ""
>                     try:
>                         assert actual_args == args[1:]
>                     except AssertionError as e:
>                         introspection += "\nArgs:\n" + text_type(e)
>                     try:
>                         assert actual_kwargs == kwargs
>                     except AssertionError as e:
>                         introspection += "\nKwargs:\n" + text_type(e)
>     
>                     if introspection:
>                         msg += "\n\npytest introspection follows:\n" + introspection
>         e = AssertionError(msg)
>         e._mock_introspection_applied = True
> >       raise e
> E       AssertionError: Expected call: mock('b', 2, {'jest'})
> E       Actual call: mock('a', 1, {'test'})
> E       
> E       pytest introspection follows:
> E       
> E       Args:
> 
> ../../BUILDROOT/python-pytest-mock-1.11.2-1.el7.x86_64/usr/lib/python3.6/site-packages/pytest_mock/plugin.py:243: AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> mocker = <pytest_mock.plugin.MockFixture object at 0x7f597696eb00>
> 
>     @pytest.mark.usefixtures("needs_assert_rewrite")
>     def test_assert_called_args_with_introspection(mocker):
>         stub = mocker.stub()
>     
>         complex_args = ("a", 1, set(["test"]))
>         wrong_args = ("b", 2, set(["jest"]))
>     
>         stub(*complex_args)
>         stub.assert_called_with(*complex_args)
>         stub.assert_called_once_with(*complex_args)
>     
>         with assert_argument_introspection(complex_args, wrong_args):
>             stub.assert_called_with(*wrong_args)
> >           stub.assert_called_once_with(*wrong_args)
> 
> tests/test_pytest_mock.py:489: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> /usr/lib64/python3.6/contextlib.py:99: in __exit__
>     self.gen.throw(type, value, traceback)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> left = ('a', 1, {'test'}), right = ('b', 2, {'jest'})
> 
>     @contextmanager
>     def assert_argument_introspection(left, right):
>         """
>         Assert detailed argument introspection is used
>         """
>         try:
>             yield
>         except AssertionError as e:
>             # this may be a bit too assuming, but seems nicer then hard-coding
>             import _pytest.assertion.util as util
>     
>             # NOTE: we assert with either verbose or not, depending on how our own
>             #       test was run by examining sys.argv
>             verbose = any(a.startswith("-v") for a in sys.argv)
>             expected = "\n  ".join(util._compare_eq_iterable(left, right, verbose))
> >           assert expected in str(e)
> E           assert 'Use -v to get the full diff' in "Expected call: mock('b', 2, {'jest'})\nActual call: mock('a', 1, {'test'})\n\npytest introspection follows:\n\nArgs:\n"
> E            +  where "Expected call: mock('b', 2, {'jest'})\nActual call: mock('a', 1, {'test'})\n\npytest introspection follows:\n\nArgs:\n" = str(AssertionError("Expected call: mock('b', 2, {'jest'})\nActual call: mock('a', 1, {'test'})\n\npytest introspection follows:\n\nArgs:\n",))
> 
> tests/test_pytest_mock.py:419: AssertionError
> _________________ test_assert_called_kwargs_with_introspection _________________
> 
> left = {'foo': {'bar': 1, 'baz': 'spam'}}
> right = {'foo': {'baz': 'bran', 'goo': 1}}
> 
>     @contextmanager
>     def assert_argument_introspection(left, right):
>         """
>         Assert detailed argument introspection is used
>         """
>         try:
> >           yield
> 
> tests/test_pytest_mock.py:410: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> mocker = <pytest_mock.plugin.MockFixture object at 0x7f59769592e8>
> 
>     @pytest.mark.usefixtures("needs_assert_rewrite")
>     def test_assert_called_kwargs_with_introspection(mocker):
>         stub = mocker.stub()
>     
>         complex_kwargs = dict(foo={"bar": 1, "baz": "spam"})
>         wrong_kwargs = dict(foo={"goo": 1, "baz": "bran"})
>     
>         stub(**complex_kwargs)
>         stub.assert_called_with(**complex_kwargs)
>         stub.assert_called_once_with(**complex_kwargs)
>     
>         with assert_argument_introspection(complex_kwargs, wrong_kwargs):
> >           stub.assert_called_with(**wrong_kwargs)
> 
> tests/test_pytest_mock.py:504: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> args = (<MagicMock spec='function' id='140022218331584'>,)
> kwargs = {'foo': {'baz': 'bran', 'goo': 1}}, __tracebackhide__ = True
> 
>     def wrap_assert_called_with(*args, **kwargs):
>         __tracebackhide__ = True
> >       assert_wrapper(_mock_module_originals["assert_called_with"], *args, **kwargs)
> 
> ../../BUILDROOT/python-pytest-mock-1.11.2-1.el7.x86_64/usr/lib/python3.6/site-packages/pytest_mock/plugin.py:253: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> __wrapped_mock_method__ = <function NonCallableMock.assert_called_with at 0x7f5977652ea0>
> args = (<MagicMock spec='function' id='140022218331584'>,)
> kwargs = {'foo': {'baz': 'bran', 'goo': 1}}, __tracebackhide__ = True
> e = AssertionError("Expected call: mock(foo={'goo': 1, 'baz': 'bran'})\nActual call: mock(foo={'bar': 1, 'baz': 'spam'})\n\npytest introspection follows:\n\nKwargs:\n",)
> msg = "Expected call: mock(foo={'goo': 1, 'baz': 'bran'})\nActual call: mock(foo={'bar': 1, 'baz': 'spam'})\n\npytest introspection follows:\n\nKwargs:\n"
> __mock_self = <MagicMock spec='function' id='140022218331584'>, actual_args = ()
> actual_kwargs = {'foo': {'bar': 1, 'baz': 'spam'}}
> introspection = '\nKwargs:\n'
> 
>     def assert_wrapper(__wrapped_mock_method__, *args, **kwargs):
>         __tracebackhide__ = True
>         try:
>             __wrapped_mock_method__(*args, **kwargs)
>             return
>         except AssertionError as e:
>             if getattr(e, "_mock_introspection_applied", 0):
>                 msg = text_type(e)
>             else:
>                 __mock_self = args[0]
>                 msg = text_type(e)
>                 if __mock_self.call_args is not None:
>                     actual_args, actual_kwargs = __mock_self.call_args
>                     introspection = ""
>                     try:
>                         assert actual_args == args[1:]
>                     except AssertionError as e:
>                         introspection += "\nArgs:\n" + text_type(e)
>                     try:
>                         assert actual_kwargs == kwargs
>                     except AssertionError as e:
>                         introspection += "\nKwargs:\n" + text_type(e)
>     
>                     if introspection:
>                         msg += "\n\npytest introspection follows:\n" + introspection
>         e = AssertionError(msg)
>         e._mock_introspection_applied = True
> >       raise e
> E       AssertionError: Expected call: mock(foo={'goo': 1, 'baz': 'bran'})
> E       Actual call: mock(foo={'bar': 1, 'baz': 'spam'})
> E       
> E       pytest introspection follows:
> E       
> E       Kwargs:
> 
> ../../BUILDROOT/python-pytest-mock-1.11.2-1.el7.x86_64/usr/lib/python3.6/site-packages/pytest_mock/plugin.py:243: AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> mocker = <pytest_mock.plugin.MockFixture object at 0x7f59769592e8>
> 
>     @pytest.mark.usefixtures("needs_assert_rewrite")
>     def test_assert_called_kwargs_with_introspection(mocker):
>         stub = mocker.stub()
>     
>         complex_kwargs = dict(foo={"bar": 1, "baz": "spam"})
>         wrong_kwargs = dict(foo={"goo": 1, "baz": "bran"})
>     
>         stub(**complex_kwargs)
>         stub.assert_called_with(**complex_kwargs)
>         stub.assert_called_once_with(**complex_kwargs)
>     
>         with assert_argument_introspection(complex_kwargs, wrong_kwargs):
>             stub.assert_called_with(**wrong_kwargs)
> >           stub.assert_called_once_with(**wrong_kwargs)
> 
> tests/test_pytest_mock.py:505: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> /usr/lib64/python3.6/contextlib.py:99: in __exit__
>     self.gen.throw(type, value, traceback)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> left = {'foo': {'bar': 1, 'baz': 'spam'}}
> right = {'foo': {'baz': 'bran', 'goo': 1}}
> 
>     @contextmanager
>     def assert_argument_introspection(left, right):
>         """
>         Assert detailed argument introspection is used
>         """
>         try:
>             yield
>         except AssertionError as e:
>             # this may be a bit too assuming, but seems nicer then hard-coding
>             import _pytest.assertion.util as util
>     
>             # NOTE: we assert with either verbose or not, depending on how our own
>             #       test was run by examining sys.argv
>             verbose = any(a.startswith("-v") for a in sys.argv)
>             expected = "\n  ".join(util._compare_eq_iterable(left, right, verbose))
> >           assert expected in str(e)
> E           assert 'Use -v to get the full diff' in "Expected call: mock(foo={'goo': 1, 'baz': 'bran'})\nActual call: mock(foo={'bar': 1, 'baz': 'spam'})\n\npytest introspection follows:\n\nKwargs:\n"
> E            +  where "Expected call: mock(foo={'goo': 1, 'baz': 'bran'})\nActual call: mock(foo={'bar': 1, 'baz': 'spam'})\n\npytest introspection follows:\n\nKwargs:\n" = str(AssertionError("Expected call: mock(foo={'goo': 1, 'baz': 'bran'})\nActual call: mock(foo={'bar': 1, 'baz': 'spam'})\n\npytest introspection follows:\n\nKwargs:\n",))
> 
> tests/test_pytest_mock.py:419: AssertionError
> _____________________________ test_standalone_mock _____________________________
> 
> testdir = <Testdir local('/tmp/pytest-of-mockbuild/pytest-0/test_standalone_mock0')>
> 
>     @pytest.mark.skipif(sys.version_info[0] < 3, reason="Py3 only")
>     def test_standalone_mock(testdir):
>         """Check that the "mock_use_standalone" is being used.
>         """
>         testdir.makepyfile(
>             """
>             def test_foo(mocker):
>                 pass
>         """
>         )
>         testdir.makeini(
>             """
>             [pytest]
>             mock_use_standalone_module = true
>         """
>         )
>         result = runpytest_subprocess(testdir)
> >       assert result.ret == 3
> E       assert 0 == 3
> E        +  where 0 = <RunResult ret=0 len(stdout.lines)=9 len(stderr.lines)=0 duration=0.28s>.ret
> 
> /builddir/build/BUILD/pytest-mock-1.11.2/tests/test_pytest_mock.py:630: AssertionError
> ----------------------------- Captured stdout call -----------------------------
> running: /usr/bin/python3 -mpytest --basetemp=/tmp/pytest-of-mockbuild/pytest-0/test_standalone_mock0/runpytest-0
>      in: /tmp/pytest-of-mockbuild/pytest-0/test_standalone_mock0
> ============================= test session starts ==============================
> platform linux -- Python 3.6.8, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
> rootdir: /tmp/pytest-of-mockbuild/pytest-0/test_standalone_mock0, inifile: tox.ini
> plugins: mock-1.11.2, cov-2.7.1, hypothesis-3.12.0
> collected 1 item
> 
> test_standalone_mock.py .                                                [100%]
> 
> =========================== 1 passed in 0.01 seconds ===========================
> _________________________ test_detailed_introspection __________________________
> 
> testdir = <Testdir local('/tmp/pytest-of-mockbuild/pytest-0/test_detailed_introspection0')>
> 
>     @pytest.mark.usefixtures("needs_assert_rewrite")
>     def test_detailed_introspection(testdir):
>         """Check that the "mock_use_standalone" is being used.
>         """
>         testdir.makepyfile(
>             """
>             def test(mocker):
>                 m = mocker.Mock()
>                 m('fo')
>                 m.assert_called_once_with('', bar=4)
>         """
>         )
>         result = testdir.runpytest("-s")
>         if NEW_FORMATTING:
>             expected_lines = [
>                 "*AssertionError: expected call not found.",
>                 "*Expected: mock('', bar=4)",
>                 "*Actual: mock('fo')",
>             ]
>         else:
>             expected_lines = [
>                 "*AssertionError: Expected call: mock('', bar=4)*",
>                 "*Actual call: mock('fo')*",
>             ]
>         expected_lines += [
>             "*pytest introspection follows:*",
>             "*Args:",
>             "*assert ('fo',) == ('',)",
>             "*At index 0 diff: 'fo' != ''*",
>             "*Use -v to get the full diff*",
>             "*Kwargs:*",
>             "*assert {} == {'bar': 4}*",
>             "*Right contains* more item*",
>             "*{'bar': 4}*",
>             "*Use -v to get the full diff*",
>         ]
> >       result.stdout.fnmatch_lines(expected_lines)
> E       Failed: nomatch: "*AssertionError: Expected call: mock('', bar=4)*"
> E           and: '============================= test session starts =============================='
> E           and: 'platform linux -- Python 3.6.8, pytest-4.6.3, py-1.8.0, pluggy-0.12.0'
> E           and: 'rootdir: /tmp/pytest-of-mockbuild/pytest-0/test_detailed_introspection0'
> E           and: 'plugins: mock-1.11.2, cov-2.7.1, hypothesis-3.12.0'
> E           and: 'collected 1 item'
> E           and: ''
> E           and: 'test_detailed_introspection.py F'
> E           and: ''
> E           and: '=================================== FAILURES ==================================='
> E           and: '_____________________________________ test _____________________________________'
> E           and: ''
> E           and: 'mocker = <pytest_mock.plugin.MockFixture object at 0x7f5976811160>'
> E           and: ''
> E           and: '    def test(mocker):'
> E           and: '        m = mocker.Mock()'
> E           and: "        m('fo')"
> E           and: ">       m.assert_called_once_with('', bar=4)"
> E       fnmatch: "*AssertionError: Expected call: mock('', bar=4)*"
> E          with: "E       AssertionError: Expected call: mock('', bar=4)"
> E       fnmatch: "*Actual call: mock('fo')*"
> E          with: "E       Actual call: mock('fo')"
> E       nomatch: '*pytest introspection follows:*'
> E           and: 'E       '
> E       fnmatch: '*pytest introspection follows:*'
> E          with: 'E       pytest introspection follows:'
> E       nomatch: '*Args:'
> E           and: 'E       '
> E       fnmatch: '*Args:'
> E          with: 'E       Args:'
> E       nomatch: "*assert ('fo',) == ('',)"
> E           and: 'E       '
> E           and: 'E       Kwargs:'
> E           and: ''
> E           and: 'test_detailed_introspection.py:4: AssertionError'
> E           and: '=========================== 1 failed in 0.01 seconds ==========================='
> E           and: ''
> E       remains unmatched: "*assert ('fo',) == ('',)"
> 
> /builddir/build/BUILD/pytest-mock-1.11.2/tests/test_pytest_mock.py:679: Failed
> ----------------------------- Captured stdout call -----------------------------
> ============================= test session starts ==============================
> platform linux -- Python 3.6.8, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
> rootdir: /tmp/pytest-of-mockbuild/pytest-0/test_detailed_introspection0
> plugins: mock-1.11.2, cov-2.7.1, hypothesis-3.12.0
> collected 1 item
> 
> test_detailed_introspection.py F
> 
> =================================== FAILURES ===================================
> _____________________________________ test _____________________________________
> 
> mocker = <pytest_mock.plugin.MockFixture object at 0x7f5976811160>
> 
>     def test(mocker):
>         m = mocker.Mock()
>         m('fo')
> >       m.assert_called_once_with('', bar=4)
> E       AssertionError: Expected call: mock('', bar=4)
> E       Actual call: mock('fo')
> E       
> E       pytest introspection follows:
> E       
> E       Args:
> E       
> E       Kwargs:
> 
> test_detailed_introspection.py:4: AssertionError
> =========================== 1 failed in 0.01 seconds ===========================
> =========================== short test summary info ============================
> FAILED tests/test_pytest_mock.py::test_assert_called_args_with_introspection
> FAILED tests/test_pytest_mock.py::test_assert_called_kwargs_with_introspection
> FAILED tests/test_pytest_mock.py::test_standalone_mock - assert 0 == 3
> FAILED tests/test_pytest_mock.py::test_detailed_introspection - Failed: nomat...
> ===================== 4 failed, 49 passed in 1.68 seconds ======================

```

**Comment by nicoddemus** [comment] 2019-10-25 14:10
Hi,

Can you run with `tox` instead? `tox` provides better run isolation, which might be the cause of your problem.

**Comment by nehaljwani** [comment] 2019-10-30 20:00
Hi @nicoddemus I don't think it has anything to do with isolation/tox. 

If I install pytest-mock and have egg-info instead of dist-info, the test fails.
If I revert https://github.com/pytest-dev/pytest-mock/commit/4a661d53656cd9935f776f92a6bc2dc3ee97f642 and use either, the test passes.

**Comment by nehaljwani** [comment] 2019-11-01 04:33
So, I finally found the bug (it is in pytest).

We need to inspect the output for the following code snippet:
```
$ cat <<EOF > check.py
import importlib_metadata
from _pytest.config import _iter_rewritable_modules

for x in importlib_metadata.distributions():
  if x.metadata['Name']=='pytest-mock':
    for _file in x.files:
      print("file: {}; module_or_pkg_name: {}".format(str(_file), list(_iter_rewritable_modules([str(_file)]))))
EOF
```
In the case of an installation with dist-info, we have:
```
file: pytest_mock-1.11.3.dev2+g1c5e8e9.d20191031.dist-info/INSTALLER; module_or_pkg_name: []
file: pytest_mock-1.11.3.dev2+g1c5e8e9.d20191031.dist-info/LICENSE; module_or_pkg_name: []
file: pytest_mock-1.11.3.dev2+g1c5e8e9.d20191031.dist-info/METADATA; module_or_pkg_name: []
file: pytest_mock-1.11.3.dev2+g1c5e8e9.d20191031.dist-info/RECORD; module_or_pkg_name: []
file: pytest_mock-1.11.3.dev2+g1c5e8e9.d20191031.dist-info/WHEEL; module_or_pkg_name: []
file: pytest_mock-1.11.3.dev2+g1c5e8e9.d20191031.dist-info/entry_points.txt; module_or_pkg_name: []
file: pytest_mock-1.11.3.dev2+g1c5e8e9.d20191031.dist-info/top_level.txt; module_or_pkg_name: []
file: pytest_mock/__init__.py; module_or_pkg_name: ['pytest_mock'] <---------- Good!
file: pytest_mock/__pycache__/__init__.cpython-36.pyc; module_or_pkg_name: []
file: pytest_mock/__pycache__/_version.cpython-36.pyc; module_or_pkg_name: []
file: pytest_mock/__pycache__/plugin.cpython-36.pyc; module_or_pkg_name: []
file: pytest_mock/_version.py; module_or_pkg_name: []
file: pytest_mock/plugin.py; module_or_pkg_name: []
```

In the case of a non-dist-info installation, we have:
```
file: .gitignore; module_or_pkg_name: []
file: .pre-commit-config.yaml; module_or_pkg_name: []
file: CHANGELOG.rst; module_or_pkg_name: []
file: HOWTORELEASE.rst; module_or_pkg_name: []
file: LICENSE; module_or_pkg_name: []
file: README.rst; module_or_pkg_name: []
file: setup.cfg; module_or_pkg_name: []
file: setup.py; module_or_pkg_name: ['setup'] <-------- ?????????????
file: tox.ini; module_or_pkg_name: []
file: .github/FUNDING.yml; module_or_pkg_name: []
file: .github/workflows/main.yml; module_or_pkg_name: []
file: src/pytest_mock/__init__.py; module_or_pkg_name: [] <-------- Hey, why u ditch me?
file: src/pytest_mock/_version.py; module_or_pkg_name: []
file: src/pytest_mock/plugin.py; module_or_pkg_name: []
file: src/pytest_mock.egg-info/PKG-INFO; module_or_pkg_name: []
file: src/pytest_mock.egg-info/SOURCES.txt; module_or_pkg_name: []
file: src/pytest_mock.egg-info/dependency_links.txt; module_or_pkg_name: []
file: src/pytest_mock.egg-info/entry_points.txt; module_or_pkg_name: []
file: src/pytest_mock.egg-info/requires.txt; module_or_pkg_name: []
file: src/pytest_mock.egg-info/top_level.txt; module_or_pkg_name: []
file: tests/test_pytest_mock.py; module_or_pkg_name: []
```

So basically, with non dist-info installations, the rewrite doesn't happen for the plugin: pytest_mock.
Relevant chunk of code is: 

https://github.com/pytest-dev/pytest/blob/b27ba977219260528f4e47c9614c129d680dee90/src/_pytest/config/__init__.py#L833-L854

**Comment by nehaljwani** [comment] 2019-11-01 04:51
The following diff makes it work as expected (although I am not sure if it has any side effects):

```diff
--- /spare/scratch/1572448662/dev/lib/python3.6/site-packages/_pytest/config/__init__.py        2019-11-01 00:50:27.543711279 -0400
+++ /spare/scratch/1572448662/dev2/lib/python3.6/site-packages/_pytest/config/__init__.py       2019-11-01 00:47:46.246713722 -0400
@@ -625,12 +625,12 @@
 def _iter_rewritable_modules(package_files):
     for fn in package_files:
         is_simple_module = "/" not in fn and fn.endswith(".py")
-        is_package = fn.count("/") == 1 and fn.endswith("__init__.py")
+        is_package = fn.endswith("__init__.py")
         if is_simple_module:
             module_name, _ = os.path.splitext(fn)
             yield module_name
         elif is_package:
-            package_name = os.path.dirname(fn)
+            package_name = os.path.basename(os.path.dirname(fn))
             yield package_name
```

**Comment by nicoddemus** [comment] 2019-11-18 20:55
Hi @nehaljwani, sorry for the delay!

Thanks for investigating this.

> If I install pytest-mock and have egg-info instead of dist-info, the test fails.

How are you installing with eggs? AFAIK eggs are somewhat deprecated now.

> The following diff makes it work as expected (although I am not sure if it has any side effects):

I suspect the `fn.count("/") == 1` is there for a good reason. You see, for some reason in the egg distribution the files are being listed as `src/pytest_mock/__init__.py`, while not in the case of the dist-info distribution.

**Comment by nehaljwani** [comment] 2019-11-19 03:28
@nicoddemus A huge chunk of python RPM packages are made that way. Unlike the Anaconda/Conda-Forge ecosystem where pip is used to install tarball contents and create conda packages, egg-info format is still widely being used.

Look at the file section at https://fedora.pkgs.org/30/fedora-x86_64/python3-pytest-mock-1.10.1-1.fc30.noarch.rpm.html
Look at the RPM spec at: https://src.fedoraproject.org/rpms/python-pytest-mock/blob/master/f/python-pytest-mock.spec

Regardless of RPMs, you can reproduce the problem quite easily. Simply do a `pip install -e .` or `python setup.py develop` in the source checkout of pytest-mock and you'll be able to reproduce this problem easily.

**Comment by nicoddemus** [comment] 2019-11-19 12:35
> Regardless of RPMs, you can reproduce the problem quite easily. Simply do a pip install -e . or python setup.py develop in the source checkout of pytest-mock and you'll be able to reproduce this problem easily.

I see, thanks for the detailed explanation! This seems to be a problem in pytest then. Could you open a new issue on pytest's repo so we can move the discussion over there? Thanks!

**Comment by nehaljwani** [comment] 2019-12-01 20:39
Opened: https://github.com/pytest-dev/pytest/issues/6301

**Comment by felixonmars** [comment] 2019-12-27 23:56
Now fixed in upstream pytest. I think this issue can be closed.

**Comment by nicoddemus** [comment] 2020-01-04 13:45
Thanks for the ping. 👍

**Closed by nicoddemus** 2020-01-04 13:45 UTC
Labels: question
